// Code generated by protoc-gen-go. DO NOT EDIT.
// source: paxos.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Term struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	No                   int64    `protobuf:"varint,2,opt,name=no,proto3" json:"no,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Term) Reset()         { *m = Term{} }
func (m *Term) String() string { return proto.CompactTextString(m) }
func (*Term) ProtoMessage()    {}
func (*Term) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec356ed5fe8331d, []int{0}
}

func (m *Term) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Term.Unmarshal(m, b)
}
func (m *Term) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Term.Marshal(b, m, deterministic)
}
func (m *Term) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Term.Merge(m, src)
}
func (m *Term) XXX_Size() int {
	return xxx_messageInfo_Term.Size(m)
}
func (m *Term) XXX_DiscardUnknown() {
	xxx_messageInfo_Term.DiscardUnknown(m)
}

var xxx_messageInfo_Term proto.InternalMessageInfo

func (m *Term) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Term) GetNo() int64 {
	if m != nil {
		return m.No
	}
	return 0
}

type Vote struct {
	Term                 *Term    `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vote) Reset()         { *m = Vote{} }
func (m *Vote) String() string { return proto.CompactTextString(m) }
func (*Vote) ProtoMessage()    {}
func (*Vote) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec356ed5fe8331d, []int{1}
}

func (m *Vote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vote.Unmarshal(m, b)
}
func (m *Vote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vote.Marshal(b, m, deterministic)
}
func (m *Vote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vote.Merge(m, src)
}
func (m *Vote) XXX_Size() int {
	return xxx_messageInfo_Vote.Size(m)
}
func (m *Vote) XXX_DiscardUnknown() {
	xxx_messageInfo_Vote.DiscardUnknown(m)
}

var xxx_messageInfo_Vote proto.InternalMessageInfo

func (m *Vote) GetTerm() *Term {
	if m != nil {
		return m.Term
	}
	return nil
}

func (m *Vote) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Message struct {
	Term                 *Term                       `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"`
	Type                 int64                       `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	From                 string                      `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To                   string                      `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Ok                   bool                        `protobuf:"varint,5,opt,name=ok,proto3" json:"ok,omitempty"`
	Content              map[string]*Message_Content `protobuf:"bytes,6,rep,name=content,proto3" json:"content,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec356ed5fe8331d, []int{2}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetTerm() *Term {
	if m != nil {
		return m.Term
	}
	return nil
}

func (m *Message) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Message) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Message) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Message) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *Message) GetContent() map[string]*Message_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

type Message_Content struct {
	// Types that are valid to be assigned to Result:
	//	*Message_Content_Vote
	//	*Message_Content_Value
	Result               isMessage_Content_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Message_Content) Reset()         { *m = Message_Content{} }
func (m *Message_Content) String() string { return proto.CompactTextString(m) }
func (*Message_Content) ProtoMessage()    {}
func (*Message_Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec356ed5fe8331d, []int{2, 0}
}

func (m *Message_Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message_Content.Unmarshal(m, b)
}
func (m *Message_Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message_Content.Marshal(b, m, deterministic)
}
func (m *Message_Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message_Content.Merge(m, src)
}
func (m *Message_Content) XXX_Size() int {
	return xxx_messageInfo_Message_Content.Size(m)
}
func (m *Message_Content) XXX_DiscardUnknown() {
	xxx_messageInfo_Message_Content.DiscardUnknown(m)
}

var xxx_messageInfo_Message_Content proto.InternalMessageInfo

type isMessage_Content_Result interface {
	isMessage_Content_Result()
}

type Message_Content_Vote struct {
	Vote *Vote `protobuf:"bytes,1,opt,name=vote,proto3,oneof"`
}

type Message_Content_Value struct {
	Value string `protobuf:"bytes,2,opt,name=value,proto3,oneof"`
}

func (*Message_Content_Vote) isMessage_Content_Result() {}

func (*Message_Content_Value) isMessage_Content_Result() {}

func (m *Message_Content) GetResult() isMessage_Content_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Message_Content) GetVote() *Vote {
	if x, ok := m.GetResult().(*Message_Content_Vote); ok {
		return x.Vote
	}
	return nil
}

func (m *Message_Content) GetValue() string {
	if x, ok := m.GetResult().(*Message_Content_Value); ok {
		return x.Value
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Message_Content) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Message_Content_OneofMarshaler, _Message_Content_OneofUnmarshaler, _Message_Content_OneofSizer, []interface{}{
		(*Message_Content_Vote)(nil),
		(*Message_Content_Value)(nil),
	}
}

func _Message_Content_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Message_Content)
	// result
	switch x := m.Result.(type) {
	case *Message_Content_Vote:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Vote); err != nil {
			return err
		}
	case *Message_Content_Value:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Value)
	case nil:
	default:
		return fmt.Errorf("Message_Content.Result has unexpected type %T", x)
	}
	return nil
}

func _Message_Content_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Message_Content)
	switch tag {
	case 1: // result.vote
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Vote)
		err := b.DecodeMessage(msg)
		m.Result = &Message_Content_Vote{msg}
		return true, err
	case 2: // result.value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Result = &Message_Content_Value{x}
		return true, err
	default:
		return false, nil
	}
}

func _Message_Content_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Message_Content)
	// result
	switch x := m.Result.(type) {
	case *Message_Content_Vote:
		s := proto.Size(x.Vote)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_Content_Value:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Value)))
		n += len(x.Value)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_fec356ed5fe8331d, []int{3}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Term)(nil), "grpc.Term")
	proto.RegisterType((*Vote)(nil), "grpc.Vote")
	proto.RegisterType((*Message)(nil), "grpc.Message")
	proto.RegisterMapType((map[string]*Message_Content)(nil), "grpc.Message.ContentEntry")
	proto.RegisterType((*Message_Content)(nil), "grpc.Message.Content")
	proto.RegisterType((*Empty)(nil), "grpc.Empty")
}

func init() { proto.RegisterFile("paxos.proto", fileDescriptor_fec356ed5fe8331d) }

var fileDescriptor_fec356ed5fe8331d = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x86, 0x9b, 0xcd, 0x36, 0x69, 0x27, 0xdf, 0x27, 0xb2, 0xa8, 0x84, 0x1c, 0x24, 0x04, 0x91,
	0x80, 0x10, 0x21, 0x7a, 0x10, 0xf1, 0xa4, 0x14, 0x7a, 0xe9, 0xc1, 0x55, 0xbc, 0xc7, 0x76, 0x2c,
	0xa5, 0x4d, 0x26, 0x6c, 0xb6, 0xc5, 0xfc, 0x44, 0xff, 0x95, 0xec, 0x26, 0x42, 0x0b, 0x82, 0xb7,
	0x79, 0x77, 0x66, 0x9e, 0x79, 0x67, 0x16, 0x82, 0xba, 0xf8, 0xa4, 0x26, 0xab, 0x15, 0x69, 0x12,
	0x7c, 0xa9, 0xea, 0x79, 0x72, 0x09, 0xfc, 0x15, 0x55, 0x29, 0x8e, 0x80, 0xad, 0x16, 0xa1, 0x13,
	0x3b, 0xe9, 0x58, 0xb2, 0xd5, 0xc2, 0xe8, 0x8a, 0x42, 0x16, 0x3b, 0xa9, 0x2b, 0x59, 0x45, 0xc9,
	0x03, 0xf0, 0x37, 0xd2, 0x28, 0xce, 0x81, 0x6b, 0x54, 0xa5, 0xad, 0x0c, 0x72, 0xc8, 0x0c, 0x24,
	0x33, 0x04, 0x69, 0xdf, 0xc5, 0x09, 0x0c, 0x77, 0xc5, 0x66, 0x8b, 0xb6, 0x75, 0x2c, 0x3b, 0x91,
	0x7c, 0x31, 0xf0, 0x67, 0xd8, 0x34, 0xc5, 0xf2, 0x6f, 0x82, 0x00, 0xae, 0xdb, 0x1a, 0xfb, 0xd9,
	0x36, 0x36, 0x6f, 0x1f, 0x8a, 0xca, 0xd0, 0xb5, 0x50, 0x1b, 0x1b, 0x87, 0x9a, 0x42, 0xde, 0x39,
	0xd6, 0x64, 0x34, 0xad, 0xc3, 0x61, 0xec, 0xa4, 0x23, 0xc9, 0x68, 0x2d, 0x6e, 0xc1, 0x9f, 0x53,
	0xa5, 0xb1, 0xd2, 0xa1, 0x17, 0xbb, 0x69, 0x90, 0x47, 0xdd, 0xa8, 0xde, 0x47, 0xf6, 0xd4, 0x25,
	0x27, 0x95, 0x56, 0xad, 0xfc, 0x29, 0x8d, 0x66, 0xe0, 0xf7, 0x09, 0x11, 0x03, 0xdf, 0x91, 0xc6,
	0x43, 0xa3, 0xe6, 0x08, 0xd3, 0x81, 0xb4, 0x19, 0x71, 0x76, 0xb0, 0xec, 0x74, 0xd0, 0xaf, 0xfb,
	0x38, 0x02, 0x4f, 0x61, 0xb3, 0xdd, 0xe8, 0xe8, 0x19, 0xfe, 0xed, 0xcf, 0x11, 0xc7, 0xe0, 0xae,
	0xb1, 0xed, 0xef, 0x6c, 0x42, 0x71, 0xb5, 0xcf, 0x08, 0xf2, 0xd3, 0x5f, 0x4d, 0xf6, 0xe0, 0x7b,
	0x76, 0xe7, 0x24, 0x3e, 0x0c, 0x27, 0x65, 0xad, 0xdb, 0xfc, 0x1a, 0xfc, 0x17, 0x54, 0xbb, 0xd5,
	0x1c, 0xc5, 0x05, 0x78, 0xd3, 0xa2, 0x5a, 0x6c, 0x50, 0xfc, 0x3f, 0xe8, 0x8f, 0x82, 0x4e, 0xda,
	0x86, 0x77, 0xcf, 0x7e, 0xfc, 0xcd, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb9, 0xc2, 0xcc, 0x5e,
	0x07, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceClient interface {
	Handle(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Empty, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Handle(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/grpc.Service/Handle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
type ServiceServer interface {
	Handle(context.Context, *Message) (*Empty, error)
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_Handle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Handle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Service/Handle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Handle(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handle",
			Handler:    _Service_Handle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paxos.proto",
}
